# 日志配置
logging:
  level:
    com.spay: debug
    org.springframework: warn
server:
  port: 5151
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  profiles:
    active: druid,mqtt
  sa-token:
    token-name: cwea_token
    allow-concurrent-login: false
    token-style: uuid
#    timeout:
pwd:
  salt: $1$.cwea1031$