# 日志配置
logging:
  level:
    com.spay: debug
    org.springframework: warn
server:
  port: 5151
mqtt:
  broker: tcp://broker.emqx.io:1883
  username: emqx
  password: public
  publish_clientId: cwea_wy_publish_id
  subscribe_clientId: cwea_wy_subscribe_id
  publish_topic: mqtt/cwea_wy_publish_topic
  subscribe_topic: mqtt/cwea_wy_subscribe_topic
# ict.xsjhwy.com，端口1883
# 账号xsjhwy密码xsjhwy123456*

caiyun:
  token: pjgwFxZMzaqWSEV6
  url: https://api.caiyunapp.com
  version: v2.6
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  profiles:
    active: druid
  sa-token:
    token-name: cwea_token
    allow-concurrent-login: false
    token-style: uuid